Financial Analytics & Real Estate Market Intelligence  

Real estate companies serve a highly diverse buyer base: individual home buyers, first-time buyers, corporate and institutional investors, international buyers, and high-net-worth investors. When all of these are treated the same, the result is inefficient marketing spend, generic property recommendations, and missed investment opportunities.

- Business motivation:
  - Improve customer targeting
  - Reduce inefficient marketing spend
  - Provide better property recommendations
  - Improve investor targeting
  - Identify missed investment opportunities
- Background:
  - Real estate buyers have diverse characteristics and motivations
  - Major buyer categories include individual buyers, institutional investors,
    international buyers, high-net-worth investors, and first-time buyers
- Role of AI:
  - Use machine learning clustering techniques to discover hidden patterns
    in buyer behavior
  - Group customers into meaningful buyer segments

Project Initialization

In [1]:
#import libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
print(sklearn.__version__)

from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score

1.5.0

Import Data and Create Dataframe

First Dataset : clients.csv
Second Dataset : properties.csv

In [37]:
client = pd.read_csv("C:/Users/Chandan/Desktop/Financial-Analytics-Real-Estate/data/raw/clients.csv")
properties = pd.read_csv("C:/Users/Chandan/Desktop/Financial-Analytics-Real-Estate/data/raw/properties.csv")

In [38]:
client

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,C1996,Individual,Samantha,Brooks,6/20/1992,F,USA,Nevada,Home,1,Yes,Website
1996,C1997,Individual,Matthew,Cox,9/27/1942,M,USA,Arizona,Home,4,Yes,Website
1997,C1998,Individual,Mark,Patterson,9/13/1963,M,USA,Virginia,Home,5,Yes,Website
1998,C1999,Individual,Lawrence,Montgomery,6/15/1944,M,USA,Ohio,Home,4,Yes,Client
1999,C2000,Individual,Amanda,James,3/24/1996,F,USA,Georgia,Home,1,Yes,Agency

In [39]:
properties

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113
3,1030,1,01-01-2024,Apartment,30,743.09,"$246,172.68",Sold,C0141
4,2016,2,01-01-2024,Apartment,16,701.66,"$212,265.67",Sold,C0146
...,...,...,...,...,...,...,...,...,...
9995,200417,20,12-01-2025,Apartment,48,860.80,"$271,177.34",Available,NaN
9996,200429,20,12-01-2025,Apartment,48,860.80,"$265,186.67",Sold,C1412
9997,200430,20,12-01-2025,Apartment,48,860.80,"$288,189.74",Sold,C0504
9998,200449,20,12-01-2025,Apartment,51,1062.33,"$328,980.19",Available,NaN
9999,990014,4,12-01-2025,Apartment,13,733.19,"$217,357.63",Available,NaN

In [7]:
client.head(3)

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency

In [29]:
client.sample()

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
777,C0778,Individual,George,Pierce,1998-07-22,M,USA,California,Investment,4,Yes,Agency

In [9]:
client.shape

(2000, 12)

In [14]:
client.columns

Index(['client_id', 'client_type', 'first_name', 'last_name', 'date_of_birth',
       'gender', 'country', 'region', 'acquisition_purpose',
       'satisfaction_score', 'loan_applied', 'referral_channel'],
      dtype='object')

Data Cleaning

In [8]:
client.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   object
 1   client_type          2000 non-null   object
 2   first_name           2000 non-null   object
 3   last_name            2000 non-null   object
 4   date_of_birth        2000 non-null   object
 5   gender               2000 non-null   object
 6   country              2000 non-null   object
 7   region               2000 non-null   object
 8   acquisition_purpose  2000 non-null   object
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   object
 11  referral_channel     2000 non-null   object
dtypes: int64(1), object(11)
memory usage: 187.6+ KB

In [11]:
#Changing the data type if the date_of_birth

client['date_of_birth'] = pd.to_datetime(client['date_of_birth'], format='mixed', errors='coerce')

In [13]:
client.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   object
 1   client_type          2000 non-null   object
 2   first_name           2000 non-null   object
 3   last_name            2000 non-null   object
 4   date_of_birth        2000 non-null   datetime64[ns]
 5   gender               2000 non-null   object
 6   country              2000 non-null   object
 7   region               2000 non-null   object
 8   acquisition_purpose  2000 non-null   object
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   object
 11  referral_channel     2000 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 187.6+ KB

In [20]:
client.isnull().sum()

client_id              0
client_type            0
first_name             0
last_name              0
date_of_birth          0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

In [26]:
client.duplicated(['client_id']).sum()

0

In [30]:
cat_cols = client.columns

for col in cat_cols:
    print(f"\n--- {col} ---")
    print(client[col].value_counts(dropna=False))

--- client_id ---
client_id
C0001    1
C1330    1
C1343    1
C1342    1
C1341    1
        ..
C0662    1
C0661    1
C0660    1
C0659    1
C2000    1
Name: count, Length: 2000, dtype: int64

--- client_type ---
client_type
Individual    1897
Company        103
Name: count, dtype: int64

--- first_name ---
first_name
Carl       24
Gerald     20
Jason      19
Sarah      19
William    19
           ..
Laurel      1
Simon       1
Aniyah      1
Kamden      1
Kareem      1
Name: count, Length: 337, dtype: int64

--- last_name ---
last_name
Co         103
Howard      39
Hansen      34
Morales     34
Cox         33
          ...
Larsen       1
Stein        1
Perry        1
Mueller      1
Bailey       1
Name: count, Length: 224, dtype: int64

--- date_of_birth ---
date_of_birth
1993-06-14    3
1975-03-27    3
1973-10-24    3
1967-04-13    3
1995-11-12    3
             ..
1948-08-20    1
1977-04-25    1
1965-04-16    1
1964-12-02    1
1944-06-15    1
Name: count, Length: 1889, dtype: int64

--- gender ---
gender
M    1012
F     988
Name: count, dtype: int64

--- country ---
country
USA          1538
UK             95
Canada         85
Germany        56
France         53
Belgium        43
Mexico         40
Australia      39
Russia         36
Denmark        15
Name: count, dtype: int64

--- region ---
region
California                633
Nevada                    143
Colorado                  118
Arizona                   108
Oregon                     96
Utah                       87
Washington                 73
Virginia                   65
Texas                      56
Florida                    50
New York                   49
Georgia                    34
England                    29
Alberta                    27
Scotland                   25
Ohio                       24
Northern Ireland           24
British Columbia           20
Wales                      17
Brittany                   16
Flanders                   16
Hamburg                    16
Wallonia                   15
Ile-de-France              15
Manitoba                   15
Quebec                     14
New South Wales            13
Victoria                   13
Bavaria                    12
Brussels                   12
Berlin                     11
Nuevo Leon                 10
Provence                   10
North Rhine-Westphalia     10
Krasnodar Krai             10
Saint Petersburg           10
Jalisco                     9
Ontario                     9
Occitanie                   8
Tatarstan                   8
Baja California             7
Hesse                       7
Puebla                      7
Mexico City                 7
Western Australia           6
Capital Region              5
Novosibirsk                 5
Queensland                  4
North Denmark               4
Normandy                    4
Moscow Oblast               3
South Australia             3
Southern Denmark            3
Zealand                     2
Central Denmark             1
Kansas                      1
Wyoming                     1
Name: count, dtype: int64

--- acquisition_purpose ---
acquisition_purpose
Home          1385
Investment     615
Name: count, dtype: int64

--- satisfaction_score ---
satisfaction_score
4    417
5    405
3    404
1    395
2    379
Name: count, dtype: int64

--- loan_applied ---
loan_applied
No     1264
Yes     736
Name: count, dtype: int64

--- referral_channel ---
referral_channel
Website    1103
Agency      705
Client      192
Name: count, dtype: int64

In [31]:
for col in cat_cols:
    client[col] = (
        client[col]
        .astype(str)                              # avoid errors on NaN/non-strings
        .str.strip()                              # remove leading/trailing spaces
        .str.lower()                              # consistent case
        .str.replace(r"\s+", " ", regex=True)     # collapse multiple spaces
        .str.replace(r"[_\-]+", " ", regex=True)  # underscores/hyphens to space
    )

    # astype(str) turns NaN into the text "nan"; convert it back
    client[col] = client[col].replace({"nan": pd.NA, "none": pd.NA, "": pd.NA,
                               "n/a": pd.NA, "na": pd.NA, "null": pd.NA})

In [32]:
client['gender']

0       f
1       m
2       m
3       m
4       m
       ..
1995    f
1996    m
1997    m
1998    m
1999    f
Name: gender, Length: 2000, dtype: object

In [33]:
for col in cat_cols:
    print(f"\n{col}: {client[col].nunique()} unique values")
    print(sorted(client[col].dropna().unique()))

client_id: 2000 unique values
['c0001', 'c0002', 'c0003', 'c0004', 'c0005', 'c0006', 'c0007', 'c0008', 'c0009', 'c0010', 'c0011', 'c0012', 'c0013', 'c0014', 'c0015', 'c0016', 'c0017', 'c0018', 'c0019', 'c0020', 'c0021', 'c0022', 'c0023', 'c0024', 'c0025', 'c0026', 'c0027', 'c0028', 'c0029', 'c0030', 'c0031', 'c0032', 'c0033', 'c0034', 'c0035', 'c0036', 'c0037', 'c0038', 'c0039', 'c0040', 'c0041', 'c0042', 'c0043', 'c0044', 'c0045', 'c0046', 'c0047', 'c0048', 'c0049', 'c0050', 'c0051', 'c0052', 'c0053', 'c0054', 'c0055', 'c0056', 'c0057', 'c0058', 'c0059', 'c0060', 'c0061', 'c0062', 'c0063', 'c0064', 'c0065', 'c0066', 'c0067', 'c0068', 'c0069', 'c0070', 'c0071', 'c0072', 'c0073', 'c0074', 'c0075', 'c0076', 'c0077', 'c0078', 'c0079', 'c0080', 'c0081', 'c0082', 'c0083', 'c0084', 'c0085', 'c0086', 'c0087', 'c0088', 'c0089', 'c0090', 'c0091', 'c0092', 'c0093', 'c0094', 'c0095', 'c0096', 'c0097', 'c0098', 'c0099', 'c0100', 'c0101', 'c0102', 'c0103', 'c0104', 'c0105', 'c0106', 'c0107', 'c0108', 'c0109', 'c0110', 'c0111', 'c0112', 'c0113', 'c0114', 'c0115', 'c0116', 'c0117', 'c0118', 'c0119', 'c0120', 'c0121', 'c0122', 'c0123', 'c0124', 'c0125', 'c0126', 'c0127', 'c0128', 'c0129', 'c0130', 'c0131', 'c0132', 'c0133', 'c0134', 'c0135', 'c0136', 'c0137', 'c0138', 'c0139', 'c0140', 'c0141', 'c0142', 'c0143', 'c0144', 'c0145', 'c0146', 'c0147', 'c0148', 'c0149', 'c0150', 'c0151', 'c0152', 'c0153', 'c0154', 'c0155', 'c0156', 'c0157', 'c0158', 'c0159', 'c0160', 'c0161', 'c0162', 'c0163', 'c0164', 'c0165', 'c0166', 'c0167', 'c0168', 'c0169', 'c0170', 'c0171', 'c0172', 'c0173', 'c0174', 'c0175', 'c0176', 'c0177', 'c0178', 'c0179', 'c0180', 'c0181', 'c0182', 'c0183', 'c0184', 'c0185', 'c0186', 'c0187', 'c0188', 'c0189', 'c0190', 'c0191', 'c0192', 'c0193', 'c0194', 'c0195', 'c0196', 'c0197', 'c0198', 'c0199', 'c0200', 'c0201', 'c0202', 'c0203', 'c0204', 'c0205', 'c0206', 'c0207', 'c0208', 'c0209', 'c0210', 'c0211', 'c0212', 'c0213', 'c0214', 'c0215', 'c0216', 'c0217', 'c0218', 'c0219', 'c0220', 'c0221', 'c0222', 'c0223', 'c0224', 'c0225', 'c0226', 'c0227', 'c0228', 'c0229', 'c0230', 'c0231', 'c0232', 'c0233', 'c0234', 'c0235', 'c0236', 'c0237', 'c0238', 'c0239', 'c0240', 'c0241', 'c0242', 'c0243', 'c0244', 'c0245', 'c0246', 'c0247', 'c0248', 'c0249', 'c0250', 'c0251', 'c0252', 'c0253', 'c0254', 'c0255', 'c0256', 'c0257', 'c0258', 'c0259', 'c0260', 'c0261', 'c0262', 'c0263', 'c0264', 'c0265', 'c0266', 'c0267', 'c0268', 'c0269', 'c0270', 'c0271', 'c0272', 'c0273', 'c0274', 'c0275', 'c0276', 'c0277', 'c0278', 'c0279', 'c0280', 'c0281', 'c0282', 'c0283', 'c0284', 'c0285', 'c0286', 'c0287', 'c0288', 'c0289', 'c0290', 'c0291', 'c0292', 'c0293', 'c0294', 'c0295', 'c0296', 'c0297', 'c0298', 'c0299', 'c0300', 'c0301', 'c0302', 'c0303', 'c0304', 'c0305', 'c0306', 'c0307', 'c0308', 'c0309', 'c0310', 'c0311', 'c0312', 'c0313', 'c0314', 'c0315', 'c0316', 'c0317', 'c0318', 'c0319', 'c0320', 'c0321', 'c0322', 'c0323', 'c0324', 'c0325', 'c0326', 'c0327', 'c0328', 'c0329', 'c0330', 'c0331', 'c0332', 'c0333', 'c0334', 'c0335', 'c0336', 'c0337', 'c0338', 'c0339', 'c0340', 'c0341', 'c0342', 'c0343', 'c0344', 'c0345', 'c0346', 'c0347', 'c0348', 'c0349', 'c0350', 'c0351', 'c0352', 'c0353', 'c0354', 'c0355', 'c0356', 'c0357', 'c0358', 'c0359', 'c0360', 'c0361', 'c0362', 'c0363', 'c0364', 'c0365', 'c0366', 'c0367', 'c0368', 'c0369', 'c0370', 'c0371', 'c0372', 'c0373', 'c0374', 'c0375', 'c0376', 'c0377', 'c0378', 'c0379', 'c0380', 'c0381', 'c0382', 'c0383', 'c0384', 'c0385', 'c0386', 'c0387', 'c0388', 'c0389', 'c0390', 'c0391', 'c0392', 'c0393', 'c0394', 'c0395', 'c0396', 'c0397', 'c0398', 'c0399', 'c0400', 'c0401', 'c0402', 'c0403', 'c0404', 'c0405', 'c0406', 'c0407', 'c0408', 'c0409', 'c0410', 'c0411', 'c0412', 'c0413', 'c0414', 'c0415', 'c0416', 'c0417', 'c0418', 'c0419', 'c0420', 'c0421', 'c0422', 'c0423', 'c0424', 'c0425', 'c0426', 'c0427', 'c0428', 'c0429', 'c0430', 'c0431', 'c0432', 'c0433', 'c0434', 'c0435', 'c0436', 'c0437', 'c0438', 'c0439', 'c0440', 'c0441', 'c0442', 'c0443', 'c0444', 'c0445', 'c0446', 'c0447', 'c0448', 'c0449', 'c0450', 'c0451', 'c0452', 'c0453', 'c0454', 'c0455', 'c0456', 'c0457', 'c0458', 'c0459', 'c0460', 'c0461', 'c0462', 'c0463', 'c0464', 'c0465', 'c0466', 'c0467', 'c0468', 'c0469', 'c0470', 'c0471', 'c0472', 'c0473', 'c0474', 'c0475', 'c0476', 'c0477', 'c0478', 'c0479', 'c0480', 'c0481', 'c0482', 'c0483', 'c0484', 'c0485', 'c0486', 'c0487', 'c0488', 'c0489', 'c0490', 'c0491', 'c0492', 'c0493', 'c0494', 'c0495', 'c0496', 'c0497', 'c0498', 'c0499', 'c0500', 'c0501', 'c0502', 'c0503', 'c0504', 'c0505', 'c0506', 'c0507', 'c0508', 'c0509', 'c0510', 'c0511', 'c0512', 'c0513', 'c0514', 'c0515', 'c0516', 'c0517', 'c0518', 'c0519', 'c0520', 'c0521', 'c0522', 'c0523', 'c0524', 'c0525', 'c0526', 'c0527', 'c0528', 'c0529', 'c0530', 'c0531', 'c0532', 'c0533', 'c0534', 'c0535', 'c0536', 'c0537', 'c0538', 'c0539', 'c0540', 'c0541', 'c0542', 'c0543', 'c0544', 'c0545', 'c0546', 'c0547', 'c0548', 'c0549', 'c0550', 'c0551', 'c0552', 'c0553', 'c0554', 'c0555', 'c0556', 'c0557', 'c0558', 'c0559', 'c0560', 'c0561', 'c0562', 'c0563', 'c0564', 'c0565', 'c0566', 'c0567', 'c0568', 'c0569', 'c0570', 'c0571', 'c0572', 'c0573', 'c0574', 'c0575', 'c0576', 'c0577', 'c0578', 'c0579', 'c0580', 'c0581', 'c0582', 'c0583', 'c0584', 'c0585', 'c0586', 'c0587', 'c0588', 'c0589', 'c0590', 'c0591', 'c0592', 'c0593', 'c0594', 'c0595', 'c0596', 'c0597', 'c0598', 'c0599', 'c0600', 'c0601', 'c0602', 'c0603', 'c0604', 'c0605', 'c0606', 'c0607', 'c0608', 'c0609', 'c0610', 'c0611', 'c0612', 'c0613', 'c0614', 'c0615', 'c0616', 'c0617', 'c0618', 'c0619', 'c0620', 'c0621', 'c0622', 'c0623', 'c0624', 'c0625', 'c0626', 'c0627', 'c0628', 'c0629', 'c0630', 'c0631', 'c0632', 'c0633', 'c0634', 'c0635', 'c0636', 'c0637', 'c0638', 'c0639', 'c0640', 'c0641', 'c0642', 'c0643', 'c0644', 'c0645', 'c0646', 'c0647', 'c0648', 'c0649', 'c0650', 'c0651', 'c0652', 'c0653', 'c0654', 'c0655', 'c0656', 'c0657', 'c0658', 'c0659', 'c0660', 'c0661', 'c0662', 'c0663', 'c0664', 'c0665', 'c0666', 'c0667', 'c0668', 'c0669', 'c0670', 'c0671', 'c0672', 'c0673', 'c0674', 'c0675', 'c0676', 'c0677', 'c0678', 'c0679', 'c0680', 'c0681', 'c0682', 'c0683', 'c0684', 'c0685', 'c0686', 'c0687', 'c0688', 'c0689', 'c0690', 'c0691', 'c0692', 'c0693', 'c0694', 'c0695', 'c0696', 'c0697', 'c0698', 'c0699', 'c0700', 'c0701', 'c0702', 'c0703', 'c0704', 'c0705', 'c0706', 'c0707', 'c0708', 'c0709', 'c0710', 'c0711', 'c0712', 'c0713', 'c0714', 'c0715', 'c0716', 'c0717', 'c0718', 'c0719', 'c0720', 'c0721', 'c0722', 'c0723', 'c0724', 'c0725', 'c0726', 'c0727', 'c0728', 'c0729', 'c0730', 'c0731', 'c0732', 'c0733', 'c0734', 'c0735', 'c0736', 'c0737', 'c0738', 'c0739', 'c0740', 'c0741', 'c0742', 'c0743', 'c0744', 'c0745', 'c0746', 'c0747', 'c0748', 'c0749', 'c0750', 'c0751', 'c0752', 'c0753', 'c0754', 'c0755', 'c0756', 'c0757', 'c0758', 'c0759', 'c0760', 'c0761', 'c0762', 'c0763', 'c0764', 'c0765', 'c0766', 'c0767', 'c0768', 'c0769', 'c0770', 'c0771', 'c0772', 'c0773', 'c0774', 'c0775', 'c0776', 'c0777', 'c0778', 'c0779', 'c0780', 'c0781', 'c0782', 'c0783', 'c0784', 'c0785', 'c0786', 'c0787', 'c0788', 'c0789', 'c0790', 'c0791', 'c0792', 'c0793', 'c0794', 'c0795', 'c0796', 'c0797', 'c0798', 'c0799', 'c0800', 'c0801', 'c0802', 'c0803', 'c0804', 'c0805', 'c0806', 'c0807', 'c0808', 'c0809', 'c0810', 'c0811', 'c0812', 'c0813', 'c0814', 'c0815', 'c0816', 'c0817', 'c0818', 'c0819', 'c0820', 'c0821', 'c0822', 'c0823', 'c0824', 'c0825', 'c0826', 'c0827', 'c0828', 'c0829', 'c0830', 'c0831', 'c0832', 'c0833', 'c0834', 'c0835', 'c0836', 'c0837', 'c0838', 'c0839', 'c0840', 'c0841', 'c0842', 'c0843', 'c0844', 'c0845', 'c0846', 'c0847', 'c0848', 'c0849', 'c0850', 'c0851', 'c0852', 'c0853', 'c0854', 'c0855', 'c0856', 'c0857', 'c0858', 'c0859', 'c0860', 'c0861', 'c0862', 'c0863', 'c0864', 'c0865', 'c0866', 'c0867', 'c0868', 'c0869', 'c0870', 'c0871', 'c0872', 'c0873', 'c0874', 'c0875', 'c0876', 'c0877', 'c0878', 'c0879', 'c0880', 'c0881', 'c0882', 'c0883', 'c0884', 'c0885', 'c0886', 'c0887', 'c0888', 'c0889', 'c0890', 'c0891', 'c0892', 'c0893', 'c0894', 'c0895', 'c0896', 'c0897', 'c0898', 'c0899', 'c0900', 'c0901', 'c0902', 'c0903', 'c0904', 'c0905', 'c0906', 'c0907', 'c0908', 'c0909', 'c0910', 'c0911', 'c0912', 'c0913', 'c0914', 'c0915', 'c0916', 'c0917', 'c0918', 'c0919', 'c0920', 'c0921', 'c0922', 'c0923', 'c0924', 'c0925', 'c0926', 'c0927', 'c0928', 'c0929', 'c0930', 'c0931', 'c0932', 'c0933', 'c0934', 'c0935', 'c0936', 'c0937', 'c0938', 'c0939', 'c0940', 'c0941', 'c0942', 'c0943', 'c0944', 'c0945', 'c0946', 'c0947', 'c0948', 'c0949', 'c0950', 'c0951', 'c0952', 'c0953', 'c0954', 'c0955', 'c0956', 'c0957', 'c0958', 'c0959', 'c0960', 'c0961', 'c0962', 'c0963', 'c0964', 'c0965', 'c0966', 'c0967', 'c0968', 'c0969', 'c0970', 'c0971', 'c0972', 'c0973', 'c0974', 'c0975', 'c0976', 'c0977', 'c0978', 'c0979', 'c0980', 'c0981', 'c0982', 'c0983', 'c0984', 'c0985', 'c0986', 'c0987', 'c0988', 'c0989', 'c0990', 'c0991', 'c0992', 'c0993', 'c0994', 'c0995', 'c0996', 'c0997', 'c0998', 'c0999', 'c1000', 'c1001', 'c1002', 'c1003', 'c1004', 'c1005', 'c1006', 'c1007', 'c1008', 'c1009', 'c1010', 'c1011', 'c1012', 'c1013', 'c1014', 'c1015', 'c1016', 'c1017', 'c1018', 'c1019', 'c1020', 'c1021', 'c1022', 'c1023', 'c1024', 'c1025', 'c1026', 'c1027', 'c1028', 'c1029', 'c1030', 'c1031', 'c1032', 'c1033', 'c1034', 'c1035', 'c1036', 'c1037', 'c1038', 'c1039', 'c1040', 'c1041', 'c1042', 'c1043', 'c1044', 'c1045', 'c1046', 'c1047', 'c1048', 'c1049', 'c1050', 'c1051', 'c1052', 'c1053', 'c1054', 'c1055', 'c1056', 'c1057', 'c1058', 'c1059', 'c1060', 'c1061', 'c1062', 'c1063', 'c1064', 'c1065', 'c1066', 'c1067', 'c1068', 'c1069', 'c1070', 'c1071', 'c1072', 'c1073', 'c1074', 'c1075', 'c1076', 'c1077', 'c1078', 'c1079', 'c1080', 'c1081', 'c1082', 'c1083', 'c1084', 'c1085', 'c1086', 'c1087', 'c1088', 'c1089', 'c1090', 'c1091', 'c1092', 'c1093', 'c1094', 'c1095', 'c1096', 'c1097', 'c1098', 'c1099', 'c1100', 'c1101', 'c1102', 'c1103', 'c1104', 'c1105', 'c1106', 'c1107', 'c1108', 'c1109', 'c1110', 'c1111', 'c1112', 'c1113', 'c1114', 'c1115', 'c1116', 'c1117', 'c1118', 'c1119', 'c1120', 'c1121', 'c1122', 'c1123', 'c1124', 'c1125', 'c1126', 'c1127', 'c1128', 'c1129', 'c1130', 'c1131', 'c1132', 'c1133', 'c1134', 'c1135', 'c1136', 'c1137', 'c1138', 'c1139', 'c1140', 'c1141', 'c1142', 'c1143', 'c1144', 'c1145', 'c1146', 'c1147', 'c1148', 'c1149', 'c1150', 'c1151', 'c1152', 'c1153', 'c1154', 'c1155', 'c1156', 'c1157', 'c1158', 'c1159', 'c1160', 'c1161', 'c1162', 'c1163', 'c1164', 'c1165', 'c1166', 'c1167', 'c1168', 'c1169', 'c1170', 'c1171', 'c1172', 'c1173', 'c1174', 'c1175', 'c1176', 'c1177', 'c1178', 'c1179', 'c1180', 'c1181', 'c1182', 'c1183', 'c1184', 'c1185', 'c1186', 'c1187', 'c1188', 'c1189', 'c1190', 'c1191', 'c1192', 'c1193', 'c1194', 'c1195', 'c1196', 'c1197', 'c1198', 'c1199', 'c1200', 'c1201', 'c1202', 'c1203', 'c1204', 'c1205', 'c1206', 'c1207', 'c1208', 'c1209', 'c1210', 'c1211', 'c1212', 'c1213', 'c1214', 'c1215', 'c1216', 'c1217', 'c1218', 'c1219', 'c1220', 'c1221', 'c1222', 'c1223', 'c1224', 'c1225', 'c1226', 'c1227', 'c1228', 'c1229', 'c1230', 'c1231', 'c1232', 'c1233', 'c1234', 'c1235', 'c1236', 'c1237', 'c1238', 'c1239', 'c1240', 'c1241', 'c1242', 'c1243', 'c1244', 'c1245', 'c1246', 'c1247', 'c1248', 'c1249', 'c1250', 'c1251', 'c1252', 'c1253', 'c1254', 'c1255', 'c1256', 'c1257', 'c1258', 'c1259', 'c1260', 'c1261', 'c1262', 'c1263', 'c1264', 'c1265', 'c1266', 'c1267', 'c1268', 'c1269', 'c1270', 'c1271', 'c1272', 'c1273', 'c1274', 'c1275', 'c1276', 'c1277', 'c1278', 'c1279', 'c1280', 'c1281', 'c1282', 'c1283', 'c1284', 'c1285', 'c1286', 'c1287', 'c1288', 'c1289', 'c1290', 'c1291', 'c1292', 'c1293', 'c1294', 'c1295', 'c1296', 'c1297', 'c1298', 'c1299', 'c1300', 'c1301', 'c1302', 'c1303', 'c1304', 'c1305', 'c1306', 'c1307', 'c1308', 'c1309', 'c1310', 'c1311', 'c1312', 'c1313', 'c1314', 'c1315', 'c1316', 'c1317', 'c1318', 'c1319', 'c1320', 'c1321', 'c1322', 'c1323', 'c1324', 'c1325', 'c1326', 'c1327', 'c1328', 'c1329', 'c1330', 'c1331', 'c1332', 'c1333', 'c1334', 'c1335', 'c1336', 'c1337', 'c1338', 'c1339', 'c1340', 'c1341', 'c1342', 'c1343', 'c1344', 'c1345', 'c1346', 'c1347', 'c1348', 'c1349', 'c1350', 'c1351', 'c1352', 'c1353', 'c1354', 'c1355', 'c1356', 'c1357', 'c1358', 'c1359', 'c1360', 'c1361', 'c1362', 'c1363', 'c1364', 'c1365', 'c1366', 'c1367', 'c1368', 'c1369', 'c1370', 'c1371', 'c1372', 'c1373', 'c1374', 'c1375', 'c1376', 'c1377', 'c1378', 'c1379', 'c1380', 'c1381', 'c1382', 'c1383', 'c1384', 'c1385', 'c1386', 'c1387', 'c1388', 'c1389', 'c1390', 'c1391', 'c1392', 'c1393', 'c1394', 'c1395', 'c1396', 'c1397', 'c1398', 'c1399', 'c1400', 'c1401', 'c1402', 'c1403', 'c1404', 'c1405', 'c1406', 'c1407', 'c1408', 'c1409', 'c1410', 'c1411', 'c1412', 'c1413', 'c1414', 'c1415', 'c1416', 'c1417', 'c1418', 'c1419', 'c1420', 'c1421', 'c1422', 'c1423', 'c1424', 'c1425', 'c1426', 'c1427', 'c1428', 'c1429', 'c1430', 'c1431', 'c1432', 'c1433', 'c1434', 'c1435', 'c1436', 'c1437', 'c1438', 'c1439', 'c1440', 'c1441', 'c1442', 'c1443', 'c1444', 'c1445', 'c1446', 'c1447', 'c1448', 'c1449', 'c1450', 'c1451', 'c1452', 'c1453', 'c1454', 'c1455', 'c1456', 'c1457', 'c1458', 'c1459', 'c1460', 'c1461', 'c1462', 'c1463', 'c1464', 'c1465', 'c1466', 'c1467', 'c1468', 'c1469', 'c1470', 'c1471', 'c1472', 'c1473', 'c1474', 'c1475', 'c1476', 'c1477', 'c1478', 'c1479', 'c1480', 'c1481', 'c1482', 'c1483', 'c1484', 'c1485', 'c1486', 'c1487', 'c1488', 'c1489', 'c1490', 'c1491', 'c1492', 'c1493', 'c1494', 'c1495', 'c1496', 'c1497', 'c1498', 'c1499', 'c1500', 'c1501', 'c1502', 'c1503', 'c1504', 'c1505', 'c1506', 'c1507', 'c1508', 'c1509', 'c1510', 'c1511', 'c1512', 'c1513', 'c1514', 'c1515', 'c1516', 'c1517', 'c1518', 'c1519', 'c1520', 'c1521', 'c1522', 'c1523', 'c1524', 'c1525', 'c1526', 'c1527', 'c1528', 'c1529', 'c1530', 'c1531', 'c1532', 'c1533', 'c1534', 'c1535', 'c1536', 'c1537', 'c1538', 'c1539', 'c1540', 'c1541', 'c1542', 'c1543', 'c1544', 'c1545', 'c1546', 'c1547', 'c1548', 'c1549', 'c1550', 'c1551', 'c1552', 'c1553', 'c1554', 'c1555', 'c1556', 'c1557', 'c1558', 'c1559', 'c1560', 'c1561', 'c1562', 'c1563', 'c1564', 'c1565', 'c1566', 'c1567', 'c1568', 'c1569', 'c1570', 'c1571', 'c1572', 'c1573', 'c1574', 'c1575', 'c1576', 'c1577', 'c1578', 'c1579', 'c1580', 'c1581', 'c1582', 'c1583', 'c1584', 'c1585', 'c1586', 'c1587', 'c1588', 'c1589', 'c1590', 'c1591', 'c1592', 'c1593', 'c1594', 'c1595', 'c1596', 'c1597', 'c1598', 'c1599', 'c1600', 'c1601', 'c1602', 'c1603', 'c1604', 'c1605', 'c1606', 'c1607', 'c1608', 'c1609', 'c1610', 'c1611', 'c1612', 'c1613', 'c1614', 'c1615', 'c1616', 'c1617', 'c1618', 'c1619', 'c1620', 'c1621', 'c1622', 'c1623', 'c1624', 'c1625', 'c1626', 'c1627', 'c1628', 'c1629', 'c1630', 'c1631', 'c1632', 'c1633', 'c1634', 'c1635', 'c1636', 'c1637', 'c1638', 'c1639', 'c1640', 'c1641', 'c1642', 'c1643', 'c1644', 'c1645', 'c1646', 'c1647', 'c1648', 'c1649', 'c1650', 'c1651', 'c1652', 'c1653', 'c1654', 'c1655', 'c1656', 'c1657', 'c1658', 'c1659', 'c1660', 'c1661', 'c1662', 'c1663', 'c1664', 'c1665', 'c1666', 'c1667', 'c1668', 'c1669', 'c1670', 'c1671', 'c1672', 'c1673', 'c1674', 'c1675', 'c1676', 'c1677', 'c1678', 'c1679', 'c1680', 'c1681', 'c1682', 'c1683', 'c1684', 'c1685', 'c1686', 'c1687', 'c1688', 'c1689', 'c1690', 'c1691', 'c1692', 'c1693', 'c1694', 'c1695', 'c1696', 'c1697', 'c1698', 'c1699', 'c1700', 'c1701', 'c1702', 'c1703', 'c1704', 'c1705', 'c1706', 'c1707', 'c1708', 'c1709', 'c1710', 'c1711', 'c1712', 'c1713', 'c1714', 'c1715', 'c1716', 'c1717', 'c1718', 'c1719', 'c1720', 'c1721', 'c1722', 'c1723', 'c1724', 'c1725', 'c1726', 'c1727', 'c1728', 'c1729', 'c1730', 'c1731', 'c1732', 'c1733', 'c1734', 'c1735', 'c1736', 'c1737', 'c1738', 'c1739', 'c1740', 'c1741', 'c1742', 'c1743', 'c1744', 'c1745', 'c1746', 'c1747', 'c1748', 'c1749', 'c1750', 'c1751', 'c1752', 'c1753', 'c1754', 'c1755', 'c1756', 'c1757', 'c1758', 'c1759', 'c1760', 'c1761', 'c1762', 'c1763', 'c1764', 'c1765', 'c1766', 'c1767', 'c1768', 'c1769', 'c1770', 'c1771', 'c1772', 'c1773', 'c1774', 'c1775', 'c1776', 'c1777', 'c1778', 'c1779', 'c1780', 'c1781', 'c1782', 'c1783', 'c1784', 'c1785', 'c1786', 'c1787', 'c1788', 'c1789', 'c1790', 'c1791', 'c1792', 'c1793', 'c1794', 'c1795', 'c1796', 'c1797', 'c1798', 'c1799', 'c1800', 'c1801', 'c1802', 'c1803', 'c1804', 'c1805', 'c1806', 'c1807', 'c1808', 'c1809', 'c1810', 'c1811', 'c1812', 'c1813', 'c1814', 'c1815', 'c1816', 'c1817', 'c1818', 'c1819', 'c1820', 'c1821', 'c1822', 'c1823', 'c1824', 'c1825', 'c1826', 'c1827', 'c1828', 'c1829', 'c1830', 'c1831', 'c1832', 'c1833', 'c1834', 'c1835', 'c1836', 'c1837', 'c1838', 'c1839', 'c1840', 'c1841', 'c1842', 'c1843', 'c1844', 'c1845', 'c1846', 'c1847', 'c1848', 'c1849', 'c1850', 'c1851', 'c1852', 'c1853', 'c1854', 'c1855', 'c1856', 'c1857', 'c1858', 'c1859', 'c1860', 'c1861', 'c1862', 'c1863', 'c1864', 'c1865', 'c1866', 'c1867', 'c1868', 'c1869', 'c1870', 'c1871', 'c1872', 'c1873', 'c1874', 'c1875', 'c1876', 'c1877', 'c1878', 'c1879', 'c1880', 'c1881', 'c1882', 'c1883', 'c1884', 'c1885', 'c1886', 'c1887', 'c1888', 'c1889', 'c1890', 'c1891', 'c1892', 'c1893', 'c1894', 'c1895', 'c1896', 'c1897', 'c1898', 'c1899', 'c1900', 'c1901', 'c1902', 'c1903', 'c1904', 'c1905', 'c1906', 'c1907', 'c1908', 'c1909', 'c1910', 'c1911', 'c1912', 'c1913', 'c1914', 'c1915', 'c1916', 'c1917', 'c1918', 'c1919', 'c1920', 'c1921', 'c1922', 'c1923', 'c1924', 'c1925', 'c1926', 'c1927', 'c1928', 'c1929', 'c1930', 'c1931', 'c1932', 'c1933', 'c1934', 'c1935', 'c1936', 'c1937', 'c1938', 'c1939', 'c1940', 'c1941', 'c1942', 'c1943', 'c1944', 'c1945', 'c1946', 'c1947', 'c1948', 'c1949', 'c1950', 'c1951', 'c1952', 'c1953', 'c1954', 'c1955', 'c1956', 'c1957', 'c1958', 'c1959', 'c1960', 'c1961', 'c1962', 'c1963', 'c1964', 'c1965', 'c1966', 'c1967', 'c1968', 'c1969', 'c1970', 'c1971', 'c1972', 'c1973', 'c1974', 'c1975', 'c1976', 'c1977', 'c1978', 'c1979', 'c1980', 'c1981', 'c1982', 'c1983', 'c1984', 'c1985', 'c1986', 'c1987', 'c1988', 'c1989', 'c1990', 'c1991', 'c1992', 'c1993', 'c1994', 'c1995', 'c1996', 'c1997', 'c1998', 'c1999', 'c2000']

client_type: 2 unique values
['company', 'individual']

first_name: 337 unique values

In [35]:
client["loan_applied"] = (
    client["loan_applied"]
    .replace({"yes": 1, "no": 0})
    .infer_objects(copy=False)
)

In [36]:
client

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,c0001,individual,kareem,liu,1968 05 11,f,usa,california,home,4,1,website
1,c0002,individual,trystan,oconnor,1962 11 26,m,usa,california,home,1,0,website
2,c0003,individual,kale,gay,1959 04 07,m,usa,california,home,4,1,agency
3,c0004,individual,russell,gross,1959 11 25,m,usa,california,home,5,0,website
4,c0005,company,marleez,co,1976 02 28,m,usa,california,investment,5,0,website
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,c1996,individual,samantha,brooks,1992 06 20,f,usa,nevada,home,1,1,website
1996,c1997,individual,matthew,cox,1942 09 27,m,usa,arizona,home,4,1,website
1997,c1998,individual,mark,patterson,1963 09 13,m,usa,virginia,home,5,1,website
1998,c1999,individual,lawrence,montgomery,1944 06 15,m,usa,ohio,home,4,1,client
1999,c2000,individual,amanda,james,1996 03 24,f,usa,georgia,home,1,1,agency

Observation:

From the above data cleaning process, it is found that the client dataset  does not any missing values and not any duplicate values.But it is found that the data type of date_of_birth is object instead of data_time. So it is changed to data_time data type.

Also the loan applied is in the form of string("Yes", "No"). It is converted into integer(1 for "Yes" and 0 for "No" ) for better understanding

In [44]:
properties.head(3)

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113

In [40]:
properties.shape

(10000, 9)

In [42]:
properties.columns

Index(['listing_id', 'tower_number', 'transaction_date', 'unit_category',
       'unit_number', 'floor_area_sqft', 'sale_price', 'listing_status',
       'client_ref'],
      dtype='object')

In [43]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        10000 non-null  int64
 1   tower_number      10000 non-null  int64
 2   transaction_date  10000 non-null  object
 3   unit_category     10000 non-null  object
 4   unit_number       10000 non-null  int64
 5   floor_area_sqft   10000 non-null  float64
 6   sale_price        10000 non-null  object
 7   listing_status    10000 non-null  object
 8   client_ref        7305 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 703.3+ KB

In [45]:
#changing the data type of transaction_date(str -> date_time)
properties['transaction_date'] = pd.to_datetime(properties['transaction_date'])

In [ ]:
#changing the data type of sale_price (str-> float)
properties['sale_price'] = pd.to_numeric(
    properties['sale_price']
    .astype(str)
    .str.replace(r'[$,]', '', regex=True),
    errors='coerce'
)

In [52]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        10000 non-null  int64
 1   tower_number      10000 non-null  int64
 2   transaction_date  10000 non-null  datetime64[ns]
 3   unit_category     10000 non-null  object
 4   unit_number       10000 non-null  int64
 5   floor_area_sqft   10000 non-null  float64
 6   sale_price        10000 non-null  float64
 7   listing_status    10000 non-null  object
 8   client_ref        7305 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 703.3+ KB

In [54]:
properties.isnull().sum()

listing_id             0
tower_number           0
transaction_date       0
unit_category          0
unit_number            0
floor_area_sqft        0
sale_price             0
listing_status         0
client_ref          2695
dtype: int64

In [ ]:
# to check if  missing client_ref rows correspond to a particular listing status
print(pd.crosstab(properties["listing_status"],
                  properties["client_ref"].isnull()))

client_ref      False  True
listing_status
Available           0   2695
Sold             7305      0

In [58]:
#  Share of missing
print(properties["client_ref"].isnull().mean() * 100)

26.950000000000003

In [59]:
# Confirm the rule holds: client_ref is null if and only if the unit is Available
assert ((properties["listing_status"] == "Available") == properties["client_ref"].isnull()).all()

print("Sold units:", (properties["listing_status"] == "Sold").sum())
print("Available units:", (properties["listing_status"] == "Available").sum())

Sold units: 7305
Available units: 2695

In [60]:
# Sanity check numeric columns for impossible values
print(properties[["floor_area_sqft", "sale_price"]].describe())
print((properties["sale_price"] <= 0).sum(), (properties["floor_area_sqft"] <= 0).sum())

       floor_area_sqft     sale_price
count     10000.000000   10000.000000
mean       1139.941412  344374.678683
std         418.373967  131563.099417
min         410.710000   97402.800000
25%         782.200000  232173.642500
50%        1110.880000  330680.845000
75%        1499.000000  448852.575000
max        1957.160000  736652.270000
0 0

In [61]:
# Standardize categorical labels
for col in ["unit_category", "listing_status", "tower_number"]:
    print(properties[col].value_counts(dropna=False))

unit_category
Apartment    8547
Office       1453
Name: count, dtype: int64
listing_status
Sold         7305
Available    2695
Name: count, dtype: int64
tower_number
13    606
18    589
3     574
11    563
2     551
9     537
15    520
7     520
20    502
8     502
5     502
4     485
6     476
14    476
1     476
17    450
19    433
10    432
12    416
16    390
Name: count, dtype: int64

In [56]:
properties.duplicated().sum()

0